# Generated by Django 5.0.6 on 2024-05-23 12:00
# (A data e o hash serão diferentes para você)

from django.db import migrations
import os  # Importamos para lidar com variáveis de ambiente

# Função que será executada pela migração


def create_initial_data(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('user', 'User')

    # 1. Criar os grupos "Jogador" e "Organizador"
    # Usamos get_or_create para não dar erro se eles já existirem
    jogador_group, created = Group.objects.get_or_create(name='Jogador')
    if created:
        print('Grupo "Jogador" criado.')

    organizador_group, created = Group.objects.get_or_create(
        name='Organizador')
    if created:
        print('Grupo "Organizador" criado.')

    # 2. Criar o superusuário Organizador
    # ATENÇÃO: É uma má prática colocar senhas diretamente no código.
    # O ideal é usar variáveis de ambiente.
    ADMIN_EMAIL = 'ifsports@admin.com'
    # Pega da env ou usa o padrão
    ADMIN_PASS = os.environ.get('DEFAULT_ADMIN_PASS', 'Pass@2025')
    ADMIN_MATRICULA = 'ifsports_admin'  # Usar uma matrícula única

    # Verifica se o usuário já existe antes de tentar criar
    if not User.objects.filter(matricula=ADMIN_MATRICULA).exists():
        print(f"Criando superusuário organizador: {ADMIN_EMAIL}")

        # Usamos o manager create_superuser do seu modelo
        admin_user = User.objects.create_superuser(
            email=ADMIN_EMAIL,
            matricula=ADMIN_MATRICULA,
            nome='Organizador Padrão',
            password=ADMIN_PASS
        )

        # Adiciona o superusuário ao grupo "Organizador"
        admin_user.groups.add(organizador_group)
        print("Superusuário adicionado ao grupo 'Organizador'.")
    else:
        print(f"Superusuário com matrícula {ADMIN_MATRICULA} já existe.")


class Migration(migrations.Migration):

    # Esta migração depende da migração inicial do seu app 'user'
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        # Aqui chamamos a função que criamos
        migrations.RunPython(create_initial_data),
    ]
