# Generated by Django 5.2.1 on 2025-06-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_campus_alter_user_curso_alter_user_email'),
        ('user', '0003_initial_groups_and_organizer'),
    ]

    operations = [
    ]
